### ISSUE TITLE
Crashing when build Android

### ISSUE THREAD

**Issue by longb1997** [hngocl/BoilerplateReactNative#11]
Hi, when I would run "yarn android:dev"
Then the app crashs when open, this is logcat:

```
13878-13878/com.myapp E/SoLoader: couldn't find DSO to load: libjsc.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.myapp/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.myapp-Twfz7tVW22EIC3o3nXBWSA==/lib/x86 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
    	Native lib dir: /data/app/com.myapp-Twfz7tVW22EIC3o3nXBWSA==/lib/x86
     result: 0
--------------------------------------------------------------------------------------------------------------------------
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 11522
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.myapp.MainActivity}: java.lang.UnsupportedOperationException: Your application is configured to use RNGestureHandlerEnabledRootView which is no longer supported. You can see how to migrate to <GestureHandlerRootView /> here: https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.UnsupportedOperationException: Your application is configured to use RNGestureHandlerEnabledRootView which is no longer supported. You can see how to migrate to <GestureHandlerRootView /> here: https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot
        at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.<init>(RNGestureHandlerEnabledRootView.kt:17)
        at com.myapp.MainActivity$1.createRootView(MainActivity.java:24)
        at com.facebook.react.ReactActivityDelegate$1.createRootView(ReactActivityDelegate.java:82)
        at com.facebook.react.ReactDelegate.loadApp(ReactDelegate.java:102)
        at com.facebook.react.ReactActivityDelegate.loadApp(ReactActivityDelegate.java:91)
        at com.myapp.MainActivity$1.loadApp(MainActivity.java:29)
        at com.facebook.react.ReactActivityDelegate.onCreate(ReactActivityDelegate.java:86)
        at com.facebook.react.ReactActivity.onCreate(ReactActivity.java:46)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by longb1997** [comment]
UPDATE: I just followed [this](https://docs.swmansion.com/react-native-gesture-handler/docs/guides/migrating-off-rnghenabledroot), now it's work like a charm!
